language: node_js

node_js:
- "node"

script:
- npm run lint
- npm run build

deploy:
  provider: firebase
  token:
    secure: "qIXbKgLUOUZ1C43QWlSzOW/5ObD9CiwEtSQ0ZRwGshpHQhw1YpZXlNg6sELvQ6iZVATGPfZt+wqJpCHTahPLfzroHaSBwcNVwqzUjhnF7GAJ/236EXCa+nDX27aDcA5ygH4hTTFocCwWb3liZHm0JqptmCXlL323S660gD38HEerGFCnMjq4OsGUT3k7sWyf0MLB1mgKQilCknqeFJarYmQwk3+HiQw8Z9LgLx77I2zBwbyxMwsVoX/+CYedu5loiKm9QBN/Elvz9X19V8LRVoFuuoh69wXHZnINfgzPk9mQ11l95bixYbquGK/fMUqSlWYGDXdUir1RONLPWxCaiJCYGbYNcMUaQai3BRy8rEdxp8K4SfD1BeyOwukZkAsnZxBwXGkmJKLoKV19JMNgl6u44WhmYKlhggTfCN0AXr4EypCMREz+qXcwzWHgf1GkKJYHAYPk1EO8fU4Dky3ed9DsyroCwnw0t0Bcqe0tN0EN7qEbI9XFxcOkgcKO0UquNvEpaaF8EFfueS6L9CJrQHC6gIQXgNTRgku5FisDYasF4/ROgbmhLzBZqTvwy78lcfLj2jo4NjQqxGDIR2lirBM2hKwPuYkdUYjLiVYjAfGGFvc9kyt7rKtExUjZDAYXwdZUUrEl8PP08FNzKRxsfuGyFPX014/4YEp6X6bVmbk="
  skip_cleanup: true
  on:
    branch: master
